### ISSUE TITLE
Running r-glmnet in Python

### ISSUE THREAD

**Issue by chmc91** [conda-forge/r-glmnet-feedstock#1]
I am new to programming as a whole, so excuse some questions which would be common sense to most on here. However, I was having difficulty replicating R's glmnet results in Python with Lasso in Sklearn. So I am trying to import glmnet into python. I have a windows computer so the r-glmnet is the only one which seemed to download. However, I can not import glmnet into Spyder. (the dash in r-glmnet seems to be giving issues). Is there any documentation on how to import this appropriately and how to call the functions which would be related to R?

**Comment by MohamedElrefai** [comment]
first install [rpy2](https://anaconda.org/r/rpy2) from anaconda 
`conda install -c r rpy2 `
then you can import it by this code:
`import rpy2.robjects as robjects`
` from rpy2.robjects.packages import importr`
` glmnet = importr('glmnet')`

**Comment by mfansler** [comment]
Closing as stale. Note that these days `r` channel is not maintained. A contemporary solution should use `conda-forge` channel.
